#!/usr/bin/env bash
#
# Generate lib/secure-udp/src/secure_udp_cloud_key.h from the canonical cloud
# P-256 public key (SPKI PEM). The pinned key is the protocol's source-of-truth
# cloud key from the constrained-device-service repo (spec §2/§11) — NOT an
# operational tunable. Regenerate this header whenever that key rotates.
#
# Usage: scripts/gen-cloud-key-header.sh <cloud-pub.pem>
set -euo pipefail

PEM="${1:-}"
if [[ -z "$PEM" || ! -f "$PEM" ]]; then
	echo "usage: $0 <cloud-pub.pem>" >&2
	exit 1
fi

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/lib/secure-udp/src/secure_udp_cloud_key.h"

# P-256 SPKI DER ends with the BIT STRING contents 0x04 ‖ X(32) ‖ Y(32).
# micro-ecc wants the 64-byte X‖Y with the 0x04 prefix stripped.
XY_HEX="$(openssl ec -pubin -in "$PEM" -pubout -outform DER 2>/dev/null | tail -c 64 | xxd -p -c 64)"
if [[ "${#XY_HEX}" -ne 128 ]]; then
	echo "error: expected 64 bytes (128 hex chars) of X||Y, got ${#XY_HEX} chars" >&2
	exit 1
fi

# Format as 0x.. bytes, 12 per tab-indented line.
FORMATTED="$(echo "$XY_HEX" | fold -w2 | sed 's/^/0x/' | \
	awk '{printf (NR%12==1?"    ":""); printf "%s,%s", $0, (NR%12==0?"\n":" ")}')"

{
	echo "// AUTO-GENERATED by scripts/gen-cloud-key-header.sh — do not edit by hand."
	echo "// Pinned dedicated cloud P-256 public key (raw X‖Y, micro-ecc layout)."
	echo "// Source of truth: the cloud public key committed to constrained-device-service"
	echo "// (spec §2/§11). Regenerate from the canonical PEM on key rotation."
	echo "#pragma once"
	echo ""
	echo "#include <stdint.h>"
	echo ""
	echo "namespace particle::secure_udp {"
	echo ""
	echo "static const uint8_t kCloudPublicKeyXY[64] = {"
	echo "$FORMATTED" | sed 's/[[:space:]]*$//'
	echo "};"
	echo ""
	echo "} // namespace particle::secure_udp"
} > "$OUT"

echo "wrote $OUT"
